[package]
edition = "2024"
name = "rubify"
version = "0.1.0"

[features]
default = ["pinyin"]
pinyin = ["dep:pinyin"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
font-types = "0.10"
fontcull = "2.0"
fontcull-font-types = "0.10"
fontcull-klippa = "0.1"
fontcull-read-fonts = "0.38"
kurbo = "0.12"
pinyin = { version = "0.11", optional = true }
read-fonts = { version = "*", features = ["experimental_traverse"] }
skrifa = "0.39"
woofwoof = "1.0"
write-fonts = "0.44"
