[package]
edition = "2024"
name = "pinyinify"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
font-types = "*"
fontcull = "2.0.0"
fontcull-font-types = "0.10.2"
fontcull-klippa = "0.1.2"
fontcull-read-fonts = "0.38.0"
kurbo = "0.12"
pinyin = "0.11"
read-fonts = { version = "*", features = ["experimental_traverse"] }
skrifa = "*"
woofwoof = "1.0.2"
write-fonts = "*"
